// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgbxpjhpgrvcgyagofqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnYnhwamhwZ3J2Y2d5YWdvZnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTUwOTQsImV4cCI6MjA2NjA5MTA5NH0.3uB1Xrxqju8h_aRlhS0yrszDXO-SlK0-52pdKIw4a68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);