// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkvwhvehaonscftgapun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdndodmVoYW9uc2NmdGdhcHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzg1OTUsImV4cCI6MjA2MzcxNDU5NX0.OQHU0xQG0PnRTvj5al7Mpi2c8bomCLuO3AFt_wHwU20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);